services:
- name: chinchilla-fleet
  plan: pro
  type: web
  env: docker
  scaling:
    minInstances: 1
    maxInstances: 5
    targetMemoryPercent: 60 # optional if targetCPUPercent is set
    targetCPUPercent: 60 # optional if targetMemory is set
  healthCheckPath: /healthz
  envVars:
  - key: FLEET_MYSQL_ADDRESS
    fromService:
      name: chinchilla-fleet-mysql
      type: pserv
      property: hostport
  - key: FLEET_MYSQL_DATABASE
    fromService:
      name: chinchilla-fleet-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: FLEET_MYSQL_PASSWORD
    fromService:
      name: chinchilla-fleet-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
  - key: FLEET_MYSQL_USERNAME
    fromService:
      name: chinchilla-fleet-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: FLEET_REDIS_ADDRESS
    fromService:
      name: chinchilla-fleet-redis
      type: pserv
      property: hostport
  - key: FLEET_SERVER_TLS
    value: false
  - key: FLEET_BETA_SOFTWARE_INVENTORY
    value: 1
  - key: FLEET_LICENSE_KEY
    value: FIXME
  - key: FLEET_VULNERABILITIES_DATABASES_PATH
    value: /home/fleet
  - key: PORT
    value: 8080

- name: chinchilla-fleet-mysql
  plan: standard
  type: pserv
  env: docker
  repo: https://github.com/render-examples/mysql
  branch: mysql-5
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 50
  envVars:
  - key: MYSQL_DATABASE
    value: fleet
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
  - key: MYSQL_USER
    value: fleet

- name: chinchilla-fleet-redis
  plan: standard
  type: pserv
  env: docker
  repo: https://github.com/render-examples/redis
  disk:
    name: redis
    mountPath: /var/lib/redis
    sizeGB: 10
